### ISSUE TITLE
without ATSHA204A

### ISSUE THREAD

**Issue by garudaonekh** [RonMcKay/capacitive-soil-moisture-sensor#3]
hi, can i use it without this ATSHA204A?

**Comment by adfx** [comment]
For sure you can. Maybe you need to adopt the code a bit

**Comment by RonMcKay** [comment]
Yes, you can do that without a problem.
If you are using the MySensors framework just comment out `#define MY_SIGNING_ATSHA204` in the code and you can leave away the ATSHA204A as well as the accompanying resistor.
You can also use `#define MY_SIGNING_SOFT` for software signing.

Please be aware that sensors that are placed outside and accessible to others **can be a security risk** when not handled properly. You can read more about that topic [here](https://www.mysensors.org/about/signing).
